### PR TITLE
Add procedure about local setup in README

### PR DESCRIPTION
**Pull request by freddiefujiwara**
This is a solution of  #36 
Should I summarize these commits?
Any suggestions are welcome for me.

### CODE REVIEW

**Comment by dotneet** [comment]
Hi @freddiefujiwara,
Thank you for submitting PR!

Chromy doesn't require a user to start Chrome before use Chromy.
Because Chromy starts Chrome automatically by [chrome-launcher](https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher).

**Comment by freddiefujiwara** [comment]
HI @dotneet 
thanks for quickly replying
you mean it doesn't need my PR?
if so I'll close it 
:-)

**Comment by dotneet** [comment]
the explanation in your PR is useful in a specific situation.
But I think no need to describe it in README.md.

**Comment by freddiefujiwara** [comment]
@dotneet 
OK understood.
can I close it ?

**Comment by dotneet** [comment]
if you find another problem please open the issue or submit PR.
Thanks.

**Comment by jbergstroem** [comment]
@dotneet I don't think `chrome-launcher` covers running chrome in a docker instance which likely is going to be more common in CI and similar.

**Pull request closed without merging**
