### PR TITLE
Add babel for backward compatibility

### PR DESCRIPTION
**Pull request by NimaSoroush**

### CODE REVIEW

**Comment by dotneet** [comment]
Hi @NimaSoroush 
Thank you for submitting PR!

I merged your PR with local environment and tested with generated files, then I got errors such as:

```bash
$node -v
v7.6.0

$mocha test/evaluate.js

  evaluate
    1) can return any type
after
    2) "after each" hook for "can return any type"


  0 passing (12ms)
  2 failing

  1) evaluate can return any type:
     ReferenceError: regeneratorRuntime is not defined
      at Chromy.goto (dist/index.js:457:14)
      at ChainObject.end (node_modules/async-chain-proxy/src/index.js:31:51)
      at Proxy.<anonymous> (node_modules/async-chain-proxy/src/index.js:49:27)
      at Context.it (test/evaluate.js:26:12)

  2) evaluate "after each" hook for "can return any type":
     ReferenceError: regeneratorRuntime is not defined
      at Function.cleanup (dist/index.js:2141:14)
      at Context.afterEach (test/evaluate.js:8:18)
```

Do you have any ideas to fix this errors?

**Comment by NimaSoroush** [comment]
Hi @dotneet:

Some more work needed to be done on async-chain-proxy function. I raised a PR + comment on your question here: https://github.com/OnetapInc/async-chain-proxy/pull/1

**Comment by dotneet** [comment]
Hi @NimaSoroush 
Thanks for the answer. I got it.

To pass all the tests I needed following work.

```bash
npm i --save-dev babel-plugin-transform-builtin-extend
```

.babelrc
```json
{
  "presets": ["es2015"],
  "plugins": [
    "syntax-async-functions",
    "transform-regenerator",
    [
      "transform-runtime",
      {"polyfill": false, "regenerator": true}
    ],
    [
      "babel-plugin-transform-builtin-extend", {
      globals: ["Error", "Array"]
    }]
  ]
}
```

Would this configuration work on your environment?
if there are no problem, I would like to merge your PR and this configuration.

**Comment by NimaSoroush** [comment]
Hi @dotneet:

Wondering if you used this config with my changes in place for `async-chain-proxy` or without it. I couldn't make them run with my changes for `async-chain-proxy` in place.

**Comment by NimaSoroush** [comment]
One more comment. to be able to use transform-runtime with your project scope you have to `npm install --save-dev babel-plugin-transform-runtime` otherwise it will throw: 
```
ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/nimasoroush/Documents/projects/external/chromy/.babelrc" at 2, attempted to resolve relative
to "/Users/nimasoroush/Documents/projects/external/chromy"
    at /Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158
:20)
    at OptionManager.mergeOptions (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:23
4:36)
    at OptionManager.init (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-cli/lib/babel/util.js:50:22)
    at Object.compile (/Users/nimasoroush/Documents/projects/external/chromy/node_modules/babel-cli/lib/babel/util.js:59:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromy@0.2.10 build: `babel src --source-maps --out-dir dist --ignore '**/*.test.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromy@0.2.10 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nimasoroush/.npm/_logs/2017-06-29T13_16_57_622Z-debug.log
```
Can you confirm this too?

**Comment by NimaSoroush** [comment]
Can you confirm if your config passes with my test refactoring?

**Comment by dotneet** [comment]
I tested latest your repository with node v7.x and v8.x.
my configuration passes.

**Comment by dotneet** [comment]
I didn't confirm the problem about transform-runtime with node7.x but it reproduce with node6.x.
When merge my configuration, I will add transform-runtime to package.json.

**Comment by NimaSoroush** [comment]
In that case I am happy to get these PR through and you add your configuration on top of it. Thanks @dotneet

**Comment by dotneet** [comment]
I submit PR to your master branch. https://github.com/NimaSoroush/chromy/pull/1
Please check if it does work well in your environment.

one test is failed, but It can't be avoided with es5.
I will fix this test later.

**Comment by dotneet** [comment]
Are you going to add another changes on this PR?
Otherwise I merge this after last check.

**Comment by NimaSoroush** [comment]
No, That is all. Thanks for accepting my PR, @dotneet

**Comment by dotneet** [comment]
Thanks for your work!

**Pull request merged**
