### PR TITLE
evaluate method can accept arguments

### LINKED ISSUE #33: `evaluate` not accepting args
The test below should return 1.
Running `document.querySelectorAll("div.content").length` in the console on google.com returns 1.
It appears the Chromy does not yet support args passed in to `evaluate` (like nightmarejs).

```const Chromy = require('chromy')

let chromy = new Chromy({visible:true})

var selector = "div.content";

chromy.chain()
	.goto('https://www.google.com/')
	.evaluate( function(selector) {
		return document.querySelectorAll(selector).length;
	}, selector)
	.result((r) => console.log("selector length: " + r))
	.end()
	.then(_ => chromy.close())
```

### PR DESCRIPTION
**Pull request by TechQuery**
- [x] Add `.evaluate(func, paramArray)` to resolve #33
 - [x] API documents generated by [JSdoc](http://usejsdoc.org/) & [DocDash](http://clenemt.github.io/docdash/)

### CODE REVIEW

**Comment by TechQuery** [comment]
@dotneet Is there any problem about this PR ?

**Comment by dotneet** [comment]
@TechQuery Sorry for my late response.
This PR is great improvement!
Thanks!

**Comment by dotneet** [comment]
v0.5.7 including this patch has been published now.
thanks.

**Comment by TechQuery** [comment]
@dotneet You can host `/docs` folder by **GitHub Pages** to show **JS API document** online.

**Comment by TechQuery** [comment]
@dotneet To complete all the **JSDoc comment** in source code can make `ReadMe.md` simpler, the Home page (API document) clearer and the Source code more semantic.

And I found a little bug:

> I wrote zero `console.log()` in this PR, but when I passed arguments to **the function to be evaluated**, **the code generated from Babel** print *the source code of this function* by a `console.log()` statement...

Temporarily, I make `console.log = function () { };` and use `console.info()` instead in production environment...

**Pull request merged**
